openapi: 3.0.2
info:
  version: 1.0.0
  title: Demo User API
  description: >
    This is an **example** API to demonstrate features of OpenAPI specification

servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  '/users':
    $ref: 'paths/users.yaml'
  '/users/{id}':
    $ref: 'paths/users@{id}.yaml'